language: go
go:
  - 1.7
sudo: false

#Ready the project
before_install:
  - rvm install 2.2.2
install:
  # - go get -u -v github.com/spf13/hugo
  - _bin/hugo-017.sh
  #Get Hugo 0.17, as go get gets a dev version (bad)
  - gem install bundler
  - bundle install --without development --deployment --jobs=3 --retry=3 --binstubs
  #Given the Gemfile, bundle will install all the dependencies and nothing else is needed. 
cache:
  directories:
  - vendor/bundle

before_script: 
  - go vet ./...
  - go clean
script:
 - bin/compass compile -e production --force
 - ~/hugo017 version
 - ~/hugo017 
 # - bundle exec htmlproof public 
after_script:
  - _bin/deploy.sh
# branches:
#   only:
#   - master
env:
  global:
    - RESET=true
    - GH_REF=github.com/samozzy/guides.git
    - secure: "v1UHkGxZtbwTNgEYsyOm0AKYUkGmcT/F+a3i2/XhpawieDhvgy0wOJl2VjwDLo7VNw0cyuXD5FTqTvGUbwM6HZcn0+GQZALMDud7bsd3/bRxNCJ4lsfplfA/Yj+/YEn10J544tsa6dwSXT5O6YUnf0oLF3tIM2CoedV2QNOv+COL3Q5/Bzea/Gh78+Q94TuVVuWWJ9Sxejw9rxUewz8qZ/CjyVupzczW8B4HAy+D45yrX0w6IUeSZANtqSL4C7JTN32QYVvTWcyYfgTEjjyOVnnNTofGVyhRNoc6/8vk5LHiWC55awK6kt41VLq1wZ7JEucEnxc0iydefEpQu3wuF268eTBiSVVrP0rhILJa9Ud4SJw3I5bsO6y1blWN3Kw33h8qLDwPP+LL8aX/bbUF0SBDom/P1fBmxoN5eG6X978T19A6nRqFLPSZPiOQTRA5AhD0z6PGCctXibcLvd+jN8EnUXC8cG9Y95TIMPLv1iULuYzSRbnJaXSD8advhp3KtzRMRfm6BhJsNvtm0dkN28rm8UhOctr6C9KTVdcUIT7I9/wTQpeg4nWDpw+HLHVdx9S7XZbrz2aqkzV8IMl03BBxRQTF1Jr6RqoAbVTrvQi9AT79QBufn9fpjuV3FDMoGFT4q/fYH+rZ5S5pAdQxP8outNuKfYOIEWCSkx5CmCY="
