language: go
go:
- 1.7
sudo: false
before_install:
- rvm install 2.2.2
install:
- _bin/hugo-017.sh
- gem install bundler
- bundle install --without development --deployment --jobs=3 --retry=3 --binstubs
cache:
  directories:
  - vendor/bundle
before_script:
- go vet ./...
- go clean
script:
- bin/compass compile -e production --force
- "~/hugo017 version"
- "~/hugo017"
after_success:
- _bin/deploy.sh
env:
  global:
  - RESET=true
  - GH_REF=github.com/samozzy/guides.git
  - secure: vOSclb94xZfn+KvJxJkQIn69F1vVXZigbxeJAG1Wdyl+dXQr2Pdr5LHJ2O2eF2Bh2yx1OMUh7eWHzaQLkDQsdgrnuxi0VFHlbRsakGfDfIvSoVordb5Tuw4PE2HHZUBbWOJDB4HkqygER59VnRov9FA5xAd/kkU8amIuAUWW9p86Hl3g5T5ooOKpZc97I95hm+yP2swiN87Rdaau15XebR4nNPVwt1wQZ3ozM0BnNnyhR316c6ejKJoeZEbJKVPtw0N4T4JgRKppFpOUNnis1bJnZEHft25002qI9NKi54vVg3Jw5mFlKx9Gh0hMgmh1AqAxXNKtLkZEVwSwlxk+Gpp29f9/HmiqGCYXwlF2KxI9xAbNA/PeDDVlCd+fsQUtcrD7Oz6gCTS57kkNBsnKgZRNygtPBmkHfu/p3NkV5oFacm9WVoDtEjjUsw5RepYsDSHeHt+TAarripRKJTyVvFX6gDmXm5Nh42Vl7VJzgxB4+XISCT3eJQetjF9VfsSQToNhzcqP+MktkwAB/6HHRR8z8YfnTDmVaIUaijJwMMat4dWSQw77amPRt5SfGHDH7kDcfBiqjaTo13d7/RgbLJpqZNzKFI0AXGL6F6S+16Et/4a/EDVQLkKuwnIiojPP1BLp5PI7f2MPZQTy91/74qKvwvwG+xfaSEKhRB7sKQ0=
