baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-gb"
title = "GirlGuiding Beeston"

#Theme requirements
[author]
	name = "Benoît Benedetti"

[params]
  DateForm = "2 January, 2006"
  Description = "GirlGuiding Beeston Division is part of GirlGuiding – the leading charity for girls and young women in the UK."
  Author = "Sam Osborne"
  # email = "benoit.benedetti@gmail.com"
  # Ganalytics = "XX-00000000-0"

[taxonomies]
  tag = "tags"
  category = "categories"

# [[params.social]]
#   title = "twitter"
#   url = "https://twitter.com/humboldtux"
# [[params.social]]
#   title = "github"
#   url = "https://github.com/humboldtux"
# [[params.social]]
#   title = "facebook"
#   url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "News Posts"
  url = "/news/"
  weight = 2
