baseurl = "https://samozzy.github.io/guides"
languageCode = "en-gb"
title = "Girlguiding Beeston and Chilwell"
publishdir = "public"
copyright = "&copy; 2016 Girlguiding"

#Theme requirements
[author]
	name = "Benoît Benedetti"

[params]
  DateForm = "2 January, 2006"
  Description = "Girlguiding Beeston and Chilwell Division is part of Girlguiding – the leading charity for girls and young women in the UK."
  Author = "Sam Osborne"
  email = "test@example.com"
  # Ganalytics = "XX-00000000-0"

[taxonomies]
  tag = "tags"
  category = "categories"

[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/Beeston-and-Chilwell-Girl-Guiding-836013199868312/"
[[params.social]]
  title = "twitter"
  url = "https://twitter.com/ggbeeston"

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 2
[[menu.main]]
  name = "Groups"
  url = "/groups/"
  weight = 3
[[menu.main]]
  name = "Adults"
  url = "/adults/"
  weight = 4
[[menu.main]]
  name = "Team"
  url = "/team"
  weight = 5
[[menu.main]]
  name = "Venue"
  url = "/venue/"
  weight = 6


[blackfriday]
  plainIDAnchors = true #Now true by default in Hugo 0.16. Will be removed when Travis uses this version (TBC)
