baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-gb"
title = "GirlGuiding Beeston"
publishdir = "public"
copyright = "&copy; 2016 GirlGuiding"

#Theme requirements
[author]
	name = "Benoît Benedetti"

[params]
  DateForm = "2 January, 2006"
  Description = "GirlGuiding Beeston Division is part of GirlGuiding – the leading charity for girls and young women in the UK."
  Author = "Sam Osborne"
  email = "test@example.com"
  # Ganalytics = "XX-00000000-0"

[taxonomies]
  tag = "tags"
  category = "categories"

[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/beestongirlguiding"
[[params.social]]
  title = "twitter"
  url = "https://twitter.com/ggbeeston"

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "News Posts"
  url = "/news/"
  weight = 2

[blackfriday]
  plainIDAnchors = true #Now true by default in Hugo 0.16. Will be removed when Travis uses this version (TBC)
